### ISSUE TITLE
update

### ISSUE THREAD

**Issue by DimonYoing** [tgwaste/Mobs#10]
make dangerous mobs able to kill zombies but the creeper so that the blocks do not explode

**Comment by DimonYoing** [comment]
and improve optimization, otherwise it doesn’t lag a lot

**Comment by DimonYoing** [comment]
And how do you like the idea of adding mob eggs to the creative? Well, to make it fashionable to turn off in config.yml whether they will be in the creative or not

**Comment by DimonYoing** [comment]
can*

**Comment by DimonYoing** [comment]
?

**Comment by tgwaste** [comment]
All of this is obvious and coming 'some day'
