### ISSUE TITLE
Class "Pig" not found

### ISSUE THREAD

**Issue by edwinyoo44** [tgwaste/Mobs#13]
`
2022-02-27 [22:59:35.124] [Server thread/CRITICAL]: Error: "Class "Pig" not found" (EXCEPTION) in "plugins/Mobs-main/src/tgwaste/Mobs/Registrations" at line 63'
`

`
--- Stack trace ---
  #0 pmsrc/src/entity/EntityFactory(242): tgwaste\Mobs\Registrations::tgwaste\Mobs\{closure}(object pocketmine\world\World#32464, object pocketmine\nbt\tag\CompoundTag#312517)
  #1 pmsrc/src/world/World(2527): pocketmine\entity\EntityFactory->createFromData(object pocketmine\world\World#32464, object pocketmine\nbt\tag\CompoundTag#312517)
  #2 pmsrc/src/world/World(2482): pocketmine\world\World->initChunk(integer 123, integer -417, object pocketmine\world\format\io\ChunkData#312513)
  #3 pmsrc/src/world/World(704): pocketmine\world\World->loadChunk(integer 123, integer -417)
  #4 pmsrc/src/player/Player(746): pocketmine\world\World->registerChunkLoader(object pocketmine\player\PlayerChunkLoader#130603, integer 123, integer -417, true)
  #5 pmsrc/src/player/Player(912): pocketmine\player\Player->requestChunks()
  #6 pmsrc/src/network/mcpe/NetworkSession(1063): pocketmine\player\Player->doChunkRequests()
  #7 pmsrc/src/network/NetworkSessionManager(67): pocketmine\network\mcpe\NetworkSession->tick()
  #8 pmsrc/src/network/Network(91): pocketmine\network\NetworkSessionManager->tick()
  #9 pmsrc/src/Server(1778): pocketmine\network\Network->tick()
  #10 pmsrc/src/Server(1657): pocketmine\Server->tick()
  #11 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #12 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #13 pmsrc/src/PocketMine(327): pocketmine\server()
  #14 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.1.phar/src/Pock)
--- End of exception information ---`

**Comment by tgwaste** [comment]
Hi, which version of pocketmine?

**Comment by edwinyoo44** [comment]
> Hi, which version of pocketmine?

4.2.1

**Comment by tgwaste** [comment]
Try this .phar, unzip first.

[Mobs.phar.zip](https://github.com/tgwaste/Mobs/files/8149216/Mobs.phar.zip)

**Comment by edwinyoo44** [comment]
> Try this .phar, unzip first.
> 
> [Mobs.phar.zip](https://github.com/tgwaste/Mobs/files/8149216/Mobs.phar.zip)




2022-02-28 [22:41:28.937] [Server thread/CRITICAL]: Error: "Class "Zombie" not found" (EXCEPTION) in "plugins/58-Mobs-5c2a1/src/tgwaste/Mobs/Registrations" at line 63
--- Stack trace ---
  #0 pmsrc/src/entity/EntityFactory(242): tgwaste\Mobs\Registrations::tgwaste\Mobs\{closure}(object pocketmine\world\World#32641, object pocketmine\nbt\tag\CompoundTag#267531)
  #1 pmsrc/src/world/World(2527): pocketmine\entity\EntityFactory->createFromData(object pocketmine\world\World#32641, object pocketmine\nbt\tag\CompoundTag#267531)
  #2 pmsrc/src/world/World(2482): pocketmine\world\World->initChunk(integer -288, integer 313, object pocketmine\world\format\io\ChunkData#266743)
  #3 pmsrc/src/world/World(704): pocketmine\world\World->loadChunk(integer -288, integer 313)
  #4 pmsrc/src/player/Player(746): pocketmine\world\World->registerChunkLoader(object pocketmine\player\PlayerChunkLoader#221469, integer -288, integer 313, true)
  #5 pmsrc/src/player/Player(912): pocketmine\player\Player->requestChunks()
  #6 pmsrc/src/network/mcpe/NetworkSession(1063): pocketmine\player\Player->doChunkRequests()
  #7 pmsrc/src/network/NetworkSessionManager(67): pocketmine\network\mcpe\NetworkSession->tick()
  #8 pmsrc/src/network/Network(91): pocketmine\network\NetworkSessionManager->tick()
  #9 pmsrc/src/Server(1778): pocketmine\network\Network->tick()
  #10 pmsrc/src/Server(1657): pocketmine\Server->tick()
  #11 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #12 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #13 pmsrc/src/PocketMine(327): pocketmine\server()
  #14 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.1.phar/src/Pock)
--- End of exception information ---

**Comment by tgwaste** [comment]
No idea..  I cant reproduce this.  Im using 4.2.2.  Maybe try that.

**Comment by MrBlasyMSK** [comment]
![image](https://user-images.githubusercontent.com/85447029/158280452-28dbdd17-a831-4f52-9c92-f29419a26de0.png)
It works on [Dev #36](https://poggit.pmmp.io/babs/1efc1)
