### ISSUE TITLE
Constant creeper sound

### ISSUE THREAD

**Issue by MrBlasyMSK** [tgwaste/Mobs#2]
If you are near the creepers, you sometimes hear a sound as if they are going to start to explode, but they do not, it is rare to hear that

**Comment by tgwaste** [comment]
ive not been able to figure out why this happens, but in v1.0.3 you can set Creepers to 0 to not have them spawn.

**Comment by tgwaste** [comment]
I dont hear this anymore.  Can you please confirm?

**Comment by MrBlasyMSK** [comment]
Fixed on [Dev #36](https://poggit.pmmp.io/babs/1efc1)
