### ISSUE TITLE
Published on Poggit?

### ISSUE THREAD

**Issue by edwinyoo44** [tgwaste/Mobs#6]
This plugin is great, I think it can be published on Poggit!

https://poggit.pmmp.io/plugins

**Comment by tgwaste** [comment]
I submitted it.  We'll see what they say.  Historically I've had issues with Poggit being very anal about every little thing.  I also highly disagree with their policy to making reading private repos a default when setting up.  This is highly intrusive to user privacy.  But well see if they accept it.
